name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23-rc
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0-rc.1'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        args: --timeout 120s 

    - name: Build
      run: make zip

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: budgetcategorizer.zip
        path: budgetcategorizer.zip
